// <auto-generated />
namespace Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InquiriesYears : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InquiriesYears));
        
        string IMigrationMetadata.Id
        {
            get { return "202103211333052_InquiriesYears"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
